"use client";
import { useEffect, useState } from "react";
import { Tractor, MessageSquareText, UsersRound, UserPlus, Upload, LogIn, LogOut, Trash2, Pencil, X } from "lucide-react";
type Tab="tractors"|"enquiries"|"stories"|"users";
type Item=Record<string,unknown>;

export default function AdminPage(){
  const [authenticated,setAuthenticated]=useState<boolean|null>(null);
  const [tab,setTab]=useState<Tab>("tractors");
  const [items,setItems]=useState<Item[]>([]);
  const [editing,setEditing]=useState<Item|null>(null);
  const [status,setStatus]=useState("");
  const [saving,setSaving]=useState(false);
  const load=async(kind=tab)=>{const r=await fetch(`/api/${kind}`);const d=await r.json();setItems(Array.isArray(d)?d:d.items||[])};
  useEffect(()=>{fetch("/api/tractors",{method:"HEAD"}).then(r=>setAuthenticated(r.headers.get("x-admin")==="true"))},[]);
  useEffect(()=>{setEditing(null);setStatus("");if(authenticated)load()},[tab,authenticated]);
  async function login(fd:FormData){const r=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(fd))});const d=await r.json();if(r.ok){setAuthenticated(true);setStatus("")}else setStatus(String(d.error||"Invalid email or password."))}
  async function logout(){await fetch("/api/auth/logout",{method:"POST"});setAuthenticated(false)}
  async function upload(file:File){const media=new FormData();media.set("file",file);const r=await fetch("/api/upload",{method:"POST",body:media});if(!r.ok)throw new Error("Image upload failed");return String((await r.json()).url)}
  async function saveTractor(fd:FormData){
    setSaving(true);setStatus("");
    try{
      let image=String(fd.get("image")||"");const primary=fd.get("primaryFile");
      if(primary instanceof File&&primary.size)image=await upload(primary);
      const existingGallery=String(fd.get("galleryUrls")||"").split("\n").map(s=>s.trim()).filter(Boolean);
      const galleryFiles=fd.getAll("galleryFiles").filter((f):f is File=>f instanceof File&&f.size>0);
      const uploaded=await Promise.all(galleryFiles.map(upload));
      const payload={brand:String(fd.get("brand")),name:String(fd.get("name")),slug:String(fd.get("slug")),hp:String(fd.get("hp")),drive:String(fd.get("drive")),engine:String(fd.get("engine")),lift:String(fd.get("lift")),gearbox:String(fd.get("gearbox")),image,images:[...existingGallery,...uploaded],description:String(fd.get("description")),specs:String(fd.get("specs")||"").split("\n").map(s=>s.trim()).filter(Boolean),featured:fd.get("featured")==="on"};
      const id=editing?String(editing._id):"";const r=await fetch(id?`/api/tractors/${id}`:"/api/tractors",{method:id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(String(d.error||"Could not save tractor"));
      setStatus(id?"Tractor updated successfully.":"Tractor added successfully.");setEditing(null);await load("tractors");
    }catch(e){setStatus(e instanceof Error?e.message:"Could not save tractor")}
    finally{setSaving(false)}
  }
  async function addStory(fd:FormData){const r=await fetch("/api/stories",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(fd))});setStatus(r.ok?"Story saved.":"Could not save story.");if(r.ok)load("stories")}
  async function addUser(fd:FormData){const r=await fetch("/api/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(fd))});const d=await r.json();setStatus(r.ok?"Admin user created.":String(d.error||"Could not create user."));if(r.ok)load("users")}
  async function remove(item:Item){if(!item._id||!confirm("Delete this record permanently?"))return;const r=await fetch(`/api/${tab}/${item._id}`,{method:"DELETE"});const d=await r.json();setStatus(r.ok?"Record deleted.":String(d.error||"Could not delete record."));if(r.ok){setEditing(null);load()}}
  const text=(value:unknown)=>String(value||"");
  if(authenticated===null)return <div className="admin-loading">Loading…</div>;
  if(!authenticated)return <section className="admin-login"><form action={login}><div className="lock"><LogIn/></div><p className="eyebrow green">SECURE ACCESS</p><h1>Website management</h1><p>Sign in to manage tractors, enquiries, stories and users.</p><label>Email<input name="email" type="email" required/></label><label>Password<input name="password" type="password" required/></label><button className="button primary">Sign In</button>{status&&<p className="form-error">{status}</p>}</form></section>;
  return <section className="admin-shell"><aside><h2>Divya Tara</h2><p>Content dashboard</p><button className={tab==="tractors"?"active":""} onClick={()=>setTab("tractors")}><Tractor/>Tractors</button><button className={tab==="enquiries"?"active":""} onClick={()=>setTab("enquiries")}><MessageSquareText/>Enquiries</button><button className={tab==="stories"?"active":""} onClick={()=>setTab("stories")}><UsersRound/>Farmer stories</button><button className={tab==="users"?"active":""} onClick={()=>setTab("users")}><UserPlus/>Admin users</button><button onClick={logout}><LogOut/>Sign out</button></aside><div className="admin-main"><div className="admin-title"><div><p className="eyebrow green">ADMIN DASHBOARD</p><h1>{tab[0].toUpperCase()+tab.slice(1)}</h1></div><span>{items.length} records</span></div>
    {tab==="tractors"&&<form key={text(editing?._id)||"new"} className="tractor-editor" action={saveTractor}><div className="editor-heading"><div><h2>{editing?`Edit ${text(editing.name)}`:"Add tractor"}</h2><p>Update every visible detail and replace or add images.</p></div>{editing&&<button type="button" className="cancel-edit" onClick={()=>setEditing(null)}><X size={17}/>Cancel</button>}</div><div className="editor-grid"><label>Brand<select name="brand" defaultValue={text(editing?.brand)||"Powertrac"} required><option>Powertrac</option><option>Farmtrac</option></select></label><label>Model name<input name="name" defaultValue={text(editing?.name)} required/></label><label>Page URL slug<input name="slug" defaultValue={text(editing?.slug)} placeholder="pt-euro-50" required/></label><label>Horsepower<input name="hp" defaultValue={text(editing?.hp)} required/></label><label>Drive<input name="drive" defaultValue={text(editing?.drive)} placeholder="2WD / 4WD"/></label><label>Engine<input name="engine" defaultValue={text(editing?.engine)}/></label><label>Lift capacity<input name="lift" defaultValue={text(editing?.lift)}/></label><label>Gearbox<input name="gearbox" defaultValue={text(editing?.gearbox)}/></label><label className="wide">Description<textarea name="description" rows={3} defaultValue={text(editing?.description)}/></label><label className="wide">Specifications — one per line<textarea name="specs" rows={5} defaultValue={Array.isArray(editing?.specs)?editing.specs.join("\n"):""}/></label><div className="image-field wide"><label>Primary image URL<input name="image" defaultValue={text(editing?.image)} placeholder="https://..."/></label>{Boolean(editing?.image)&&<img src={text(editing?.image)} alt="Current tractor"/>}<label>Replace primary image<input name="primaryFile" type="file" accept="image/*"/></label></div><label className="wide">Gallery image URLs — one per line<textarea name="galleryUrls" rows={4} defaultValue={Array.isArray(editing?.images)?editing.images.join("\n"):""}/></label>{Array.isArray(editing?.images)&&editing.images.length>0&&<div className="gallery-preview wide">{editing.images.map((src,i)=><img key={`${src}-${i}`} src={String(src)} alt={`Gallery ${i+1}`}/>)}</div>}<label className="wide">Add gallery images<input name="galleryFiles" type="file" accept="image/*" multiple/></label><label className="featured-check wide"><input name="featured" type="checkbox" defaultChecked={editing?Boolean(editing.featured):true}/> Show on homepage</label></div><button className="button primary save-tractor" disabled={saving}><Upload size={17}/>{saving?"Saving…":editing?"Save changes":"Add tractor"}</button></form>}
    {tab==="stories"&&<form className="admin-form" action={addStory}><input name="farmer_name" placeholder="Farmer name" required/><input name="tractor_model" placeholder="Tractor model"/><input name="caption" placeholder="Short story headline" required/><textarea name="description" placeholder="Full story"/><input name="video_url" placeholder="Cloudinary video URL (optional)"/><button className="button primary"><Upload size={17}/> Add story</button></form>}
    {tab==="users"&&<form className="admin-form" action={addUser}><input name="email" type="email" placeholder="New admin email" required/><input name="password" type="password" minLength={8} placeholder="Temporary password (8+ characters)" required/><select name="role"><option value="admin">Admin</option><option value="editor">Editor</option></select><button className="button primary"><UserPlus size={17}/> Add user</button></form>}
    {status&&<p className="admin-status">{status}</p>}<div className="admin-table"><div className="table-row head"><span>Record</span><span>Details</span><span>Actions</span></div>{items.map((item,i)=><div className="table-row" key={text(item._id||item.slug||i)}><span className="record-name">{tab==="tractors"&&item.image?<img src={text(item.image)} alt=""/>:null}<span><strong>{text(item.email||item.name||item.farmer_name)||"Website enquiry"}</strong>{tab==="tractors"&&<small>{text(item.brand)} · {text(item.hp)} · {text(item.drive)}</small>}</span></span><span>{text(item.role||item.model||item.tractor_model||item.phone)||"—"}</span><span className="row-actions">{tab==="tractors"&&<button onClick={()=>{setEditing(item);scrollTo({top:0,behavior:"smooth"})}} aria-label="Edit tractor"><Pencil size={16}/></button>}{Boolean(item._id)&&tab!=="enquiries"&&<button className="icon-delete" onClick={()=>remove(item)} aria-label="Delete"><Trash2 size={16}/></button>}</span></div>)}</div></div></section>
}
